workers_dev = true
name = "react-router-example"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
main = "./build/server/index.js"
assets = { directory = "./build/client/" }

[[d1_databases]]
binding = "DB"
database_name = "react-router-example"
database_id = "9947a906-3feb-43cd-b1e7-3d4c366e3ada"
migrations_dir = "drizzle"
